# Pre-commit hooks - identical to CI configuration
repos:
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=100, --exclude=__pycache__]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [-r, src/, --severity-level, medium]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: python3 -m pytest tests/ -v --tb=short
        language: system
        pass_filenames: false
        always_run: true

      - id: pytest-coverage
        name: pytest-coverage
        entry: python3 -m pytest tests/ --cov=src --cov-report=term-missing --cov-fail-under=30
        language: system
        pass_filenames: false
        always_run: true