name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pre-commit pytest-cov flake8 bandit black
        
    - name: Lint with flake8
      run: |
        flake8 src/ tests/ --max-line-length=100 --exclude=__pycache__
        
    - name: Security check with bandit
      run: |
        bandit -r src/ --severity-level medium
        
    - name: Test with pytest
      run: |
        python -m pytest tests/ -v --tb=short
        
    - name: Test with coverage
      run: |
        python -m pytest tests/ --cov=src --cov-report=term-missing
EOF < /dev/null