name: Lint, Format, and Test

on:
  push:
    branches:
      - main
      - develop
      - features/**
  pull_request:
    branches:
      - main
      - develop
      - features/**

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 pytest pytest-cov

      - name: Run black (autoformat)
        run: |
          black .

      - name: Run flake8 (linter)
        run: |
          flake8 .

      - name: Run tests with coverage
        run: |
          pytest --cov=your_package_name --cov-fail-under=80

      - name: Show coverage report
        run: |
          coverage report
      - name: Generate coverage HTML report
  	run: |
	  coverage html