name: CI

on:
  push:
    branches: [ main, develop, features ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-cov

    - name: Lint with flake8
      run: |
        flake8 src/ tests/ --max-line-length=100 --exclude=__pycache__
        
    - name: Security check with bandit
      run: |
        bandit -r src/ -f json

    - name: Test with pytest
      run: |
        python -m pytest tests/ -v --tb=short

    - name: Test coverage
      run: |
        python -m pytest tests/ --cov=src --cov-report=xml --cov-report=term-missing

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false